// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlhJ7Gb1hS5TcJ4zsE9zEMRGmkX2zs2_U',
    appId: '1:104011876720:ios:98e37ef229e9cd254027b5',
    messagingSenderId: '104011876720',
    projectId: 'flutterfirstapp-d5cef',
    storageBucket: 'flutterfirstapp-d5cef.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABj2nurLRcBkAZdbloj5ah6d4pQG-j09o',
    appId: '1:104011876720:web:e28e65ea0f3c0eb04027b5',
    messagingSenderId: '104011876720',
    projectId: 'flutterfirstapp-d5cef',
    authDomain: 'flutterfirstapp-d5cef.firebaseapp.com',
    storageBucket: 'flutterfirstapp-d5cef.firebasestorage.app',
    measurementId: 'G-P0GMB3SDJ2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABj2nurLRcBkAZdbloj5ah6d4pQG-j09o',
    appId: '1:104011876720:web:e28e65ea0f3c0eb04027b5',
    messagingSenderId: '104011876720',
    projectId: 'flutterfirstapp-d5cef',
    authDomain: 'flutterfirstapp-d5cef.firebaseapp.com',
    storageBucket: 'flutterfirstapp-d5cef.firebasestorage.app',
    measurementId: 'G-P0GMB3SDJ2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlhJ7Gb1hS5TcJ4zsE9zEMRGmkX2zs2_U',
    appId: '1:104011876720:ios:98e37ef229e9cd254027b5',
    messagingSenderId: '104011876720',
    projectId: 'flutterfirstapp-d5cef',
    storageBucket: 'flutterfirstapp-d5cef.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq9_wwz8TagHngD5X1lHxgHqHapcV1i1w',
    appId: '1:104011876720:android:e94471196a16f45e4027b5',
    messagingSenderId: '104011876720',
    projectId: 'flutterfirstapp-d5cef',
    storageBucket: 'flutterfirstapp-d5cef.firebasestorage.app',
  );

}